from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base

class Worker(Base):
    __tablename__ = "workers"
    id = Column(Integer, primary_key=True, index=True)
    phone = Column(String(20), unique=True, nullable=False)
    name = Column(String(100), default="")
    hashed_password = Column(String(255), nullable=False)
    platform = Column(String(50), nullable=False)
    city = Column(String(50), nullable=False)
    zone_id = Column(String(20), nullable=False)
    zone_name = Column(String(100), nullable=False)
    zone_lat = Column(Float, nullable=False)
    zone_lon = Column(Float, nullable=False)
    zone_risk_score = Column(Integer, nullable=False)
    avg_orders = Column(Integer, default=15)
    working_hours = Column(Integer, default=8)
    upi_id = Column(String(100), nullable=False)
    risk_score = Column(Integer, default=50)
    hourly_rate = Column(Integer, default=250)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    policies = relationship("Policy", back_populates="worker")
    claims = relationship("Claim", back_populates="worker")

class Policy(Base):
    __tablename__ = "policies"
    id = Column(Integer, primary_key=True, index=True)
    worker_id = Column(Integer, ForeignKey("workers.id"), nullable=False)
    tier = Column(String(20), nullable=False)
    weekly_premium = Column(Float, nullable=False)
    coverage_cap = Column(Integer, nullable=False)
    valid_from = Column(DateTime(timezone=True), server_default=func.now())
    valid_until = Column(DateTime(timezone=True), nullable=False)
    triggers_active = Column(JSON, nullable=False)
    is_active = Column(Boolean, default=True)
    ai_insight = Column(String(500), nullable=True)
    zone_multiplier = Column(Float, nullable=False)
    claim_factor = Column(Float, default=1.0)
    consistency_bonus = Column(Float, default=0.85)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    worker = relationship("Worker", back_populates="policies")
    claims = relationship("Claim", back_populates="policy")

class Claim(Base):
    __tablename__ = "claims"
    id = Column(Integer, primary_key=True, index=True)
    worker_id = Column(Integer, ForeignKey("workers.id"), nullable=False)
    policy_id = Column(Integer, ForeignKey("policies.id"), nullable=False)
    trigger_type = Column(String(20), nullable=False)
    dcs_score = Column(Float, nullable=False)
    expected_income = Column(Float, nullable=False)
    actual_income = Column(Float, nullable=False)
    loss_amount = Column(Float, nullable=False)
    loss_percent = Column(Float, nullable=False)
    fraud_score = Column(Float, default=0)
    status = Column(String(20), default="pending")
    payout_amount = Column(Float, nullable=True)
    utr = Column(String(30), nullable=True)
    weather_signal = Column(Float, default=0)
    aqi_signal = Column(Float, default=0)
    traffic_signal = Column(Float, default=0)
    govt_alert_signal = Column(Float, default=0)
    worker_idle_signal = Column(Float, default=0)
    bio_alert_signal = Column(Float, default=0)
    conflict_signal = Column(Float, default=0)
    infra_outage_signal = Column(Float, default=0)
    fraud_layer1_passed = Column(Boolean, default=True)
    fraud_layer2_passed = Column(Boolean, default=True)
    fraud_layer3_score = Column(Float, default=0.08)
    syndicate_score = Column(Float, default=8)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    paid_at = Column(DateTime(timezone=True), nullable=True)
    worker = relationship("Worker", back_populates="claims")
    policy = relationship("Policy", back_populates="claims")

class Zone(Base):
    __tablename__ = "zones"
    id = Column(Integer, primary_key=True, index=True)
    zone_id = Column(String(20), unique=True, nullable=False)
    zone_name = Column(String(100), nullable=False)
    city = Column(String(50), nullable=False)
    risk_score = Column(Integer, nullable=False)
    lat = Column(Float, nullable=False)
    lon = Column(Float, nullable=False)
    current_dcs = Column(Float, default=0)
    active_disruption = Column(Boolean, default=False)
